

enum MaximumValues {MAX_LINE = 81, HASH_TABLE_SIZE = 307, MAX_FILE_NAME = 255, MAX_LABEL_LEN = 31};
enum Arity {NULLARY, UNARY, BINARY, JMP_CAPABLE};
enum IntRange {MINIMUM = -8192, MAXIMUM = 8191};
enum Errata {ERROR = -9000, EMPTY_LINE = -99, SUCCESS = 0, STOP = 9001, LAST_LINE = 2, MISSING = 9000, MAX_SYMBOLS_IN_FILE = 256};
enum booleans {FALSE = 0, TRUE = 1};
enum Instructions {DATA = 0, STRING = 1, ENTRY = 2, EXTERN = 3, LABEL = 4, PROCEDURE = 5, DIRECTIVE = 6};
enum Addressing {IMMEDIATE = 0 , DIRECT = 1, JUMP = 2, DIRECT_REGISTER = 3, DEFAULT = 4, JUMP_WITH_OPER = 5, JUMP_NO_OPER};
enum Status {SOURCE = 0 , DESTINATION = 1};
enum Procedures {MOV_P, CMP_P, ADD_P, SUB_P, NOT_P, CLR_P, LEA_P, INC_P, DEC_P, JMP_P, BNE_P, RED_P, PRN_P, JSR_P, RTS_P, STOP_P};
enum Statements {UNKNOWN_STATE = 0 , DIRECTIVE_STATE = 1, INSTRUCTION_STATE = 2, ENTRY_STATE = 4, EXTERN_STATE = 8, VALUE_STATE = 16, LABEL_STATE = 32, COMPLETED_STATE = 64, NOT_COMPLETE_STATE = 128};
enum AREcode {ABSOLUTE = 0, EXTERNAL = 1, RELOCATABLE = 2};
enum NodeArgc {RESERVED_KEYWORD_DATA_ARGC = 2, SYMBOL_DATA_ARGC = 3 , MACRO_DATA_ARGC = 2};
enum NodeDataType {KEYWORD_DATATYPE = 1, SYMBOL_DATATYPE = 2, MACRO_DATATYPE = 3};

